# fly.toml app configuration file generated for fly-log-shipper-gcp-test on 2024-01-22T22:49:21-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-log-shipper-nsl"
primary_region = "sea"

[metrics]
  path = "/metrics"
  port = 9598

[env]
#  If you're shipping logs to gcp, add the service account credentials to the
#  docker image and set this value to the location.
  GOOGLE_APPLICATION_CREDENTIALS = "/etc/google_creds/gcp_logging_user_credentials.json"

  ORG="noodlestreetlabs"

#  Set a queue value to prevent multiple instances from duplicate processing
#  the same log messages
  QUEUE = "nsl_gcp_logs_queue"

#  Optionally only filter logs for the specific app name, so that you're not
#  shipping out logs that other apps (e.g. this one) produce.
  SUBJECT = "logs.photos-to-slides-nsl.>"

[[services]]
  http_checks = []
  internal_port = 8686
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
  memory_mb = 256

  
