[sinks.gcp_logs]
type = "gcp_stackdriver_logs"
inputs = [ "log_json" ]
log_id = "fly-logs"
project_id = "photos-to-slides-nsl"

  [sinks.gcp_logs.resource]
  type = "global"

#[sinks.console]
#  type = "console"
#  inputs = [ "log_json" ]
#  encoding.codec = "json"
