#
# photos-to-slides
#

[sinks.gcp_logs_p2s]
type = "gcp_stackdriver_logs"
inputs = [ "log_json_p2s" ]
log_id = "fly-logs-p2s"
project_id = "photos-to-slides-nsl"
severity_key = "message.level"
credentials_path = "/etc/google_creds/gcp_logging_user_credentials_photos_to_slides.json"

[sinks.gcp_logs_p2s.resource]
type = "global"

[sinks.gcp_logs_p2s_proxy]
type = "gcp_stackdriver_logs"
inputs = [ "log_json_p2s_proxy" ]
log_id = "fly-logs-p2s-proxy"
project_id = "photos-to-slides-nsl"
severity_key = "message.level"
credentials_path = "/etc/google_creds/gcp_logging_user_credentials_photos_to_slides.json"

[sinks.gcp_logs_p2s_proxy.resource]
type = "global"

#
# marketplace-crawler
#

[sinks.gcp_logs_mpc]
type = "gcp_stackdriver_logs"
inputs = [ "log_json_mpc" ]
log_id = "fly-logs-mpc"
project_id = "marketplace-crawler-414020"
severity_key = "message.level"
credentials_path = "/etc/google_creds/gcp_logging_user_credentials_marketplace_crawler.json"

[sinks.gcp_logs_mpc.resource]
type = "global"


#[sinks.console]
#  type = "console"
#  inputs = [ "log_json" ]
#  encoding.codec = "json"
